name: Clojure CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2020.04.05'
    - name: Run linter
      run: clj-kondo --lint src
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Run build
      run: lein uberjar
    - name: Prepare SSH
      run: mkdir ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        echo "${{ secrets.SSH_KEY }}" > key.pem
        chmod 400 key.pem
    - name: Deploy to EC2
      run: scp -i key.pem target/tag-data-relay-0.1.0-SNAPSHOT-standalone.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/tag-data-relay/
