name: Clojure CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2020.04.05'
    - name: Run linter
      run: clj-kondo --lint src
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Run build
      run: lein uberjar
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "target/tag-data-relay-0.1.0-SNAPSHOT-standalone.jar"
        target: "tag-data-relay"
    - name: Start app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: kill %1 && java -jar tag-data-relay/target/tag-data-relay-0.1.0-SNAPSHOT-standalone.jar &