name: Clojure CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2020.04.05'
      run: clj-kondo --lint src
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Deploy to Heroku
      if: ${{ github.event_name == 'push' }}
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "tag-data-relay"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        healthcheck: "https://tag-data-relay.herokuapp.com/health"
        checkstring: "ok"
        rollbackonhealthcheckfailed: true